resources:
- name: deploy-cube-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf_username}}
    password: {{cf_password}}
    organization: seattle-beach
    space: cube-drafter
- name: cube-ci
  type: git
  source:
    uri: git@github.com:seattle-beach/cube-ci.git
    branch: master
    private_key: {{cube_ci_key}}
- name: cube-untap
  type: git
  source:
    uri: git@github.com:seattle-beach/cube-untap.git
    branch: master
    private_key: {{cube_untap_key}}
- name: cube-draft
  type: git
  source:
    uri: git@github.com:seattle-beach/cube-draft.git
    branch: master
    private_key: {{cube_draft_key}}
- name: pivotal-tracker
  type: tracker
  source:
    token: {{pivotal_tracker_token}}
    project_id: "2185360"
    tracker_url: https://www.pivotaltracker.com

jobs:
- name: cube-untap
  plan:
    - aggregate:
      - get: cube-ci
        trigger: true
      - get: cube-untap
        trigger: true
    - task: test-and-build
      file: cube-ci/tasks/cube-untap/test-build.yml
    - put: deploy-cube-untap-integ
      resource: deploy-cube-app
      params:
        path: compiledApp/cube.jar
        manifest: cube-untap/manifest.yml
        current_app_name: cube-untap-integ

- name: cube-draft-test
  plan:
    - aggregate:
      - get: cube-ci
        trigger: true
      - get: cube-draft
        trigger: true
    - task: test
      file: cube-ci/tasks/cube-draft/test.yml

- name: cube-draft-deploy-integ
  serial: true
  plan:
    - aggregate:
      - get: cube-ci
        trigger: true
        passed: ["cube-draft-test"]
      - get: cube-draft
        trigger: true
        passed: ["cube-draft-test"]
    - task: build
      file: cube-ci/tasks/cube-draft/build.yml
    - put: deploy-cube-draft-integ
      resource: deploy-cube-app
      params:
        manifest: cube-draft-build/manifest.yml
        current_app_name: cube-draft-integ

- name: integration-tests
  serial: true
  plan:
    - aggregate:
      - get: cube-ci
        trigger: true
        passed: ["cube-draft-deploy-integ","cube-untap"]
      - get: cube-draft
        trigger: true
        passed: ["cube-draft-deploy-integ"]
      - get: cube-untap
        trigger: true
        passed: ["cube-untap"]
    - task: integration
      file: cube-ci/tasks/cube-draft/integration.yml

- name: deploy-to-prod
  serial: true
  plan:
    - aggregate:
      - get: cube-ci
        trigger: true
        passed: ["integration-tests"]
      - get: cube-draft
        trigger: true
        passed: ["integration-tests"]
      - get: cube-untap
        trigger: true
        passed: ["integration-tests"]
    - aggregate:
      - task: build-cube-draft
        file: cube-ci/tasks/cube-draft/build.yml
      - task: build-cube-untap
        file: cube-ci/tasks/cube-untap/test-build.yml
    - aggregate:
      - put: deploy-cube-draft-prod
        resource: deploy-cube-app
        params:
          manifest: cube-draft-build/manifest.yml
          current_app_name: cube-draft
      - put: deploy-cube-untap-prod
        resource: deploy-cube-app
        params:
          path: compiledApp/cube.jar
          manifest: cube-untap/manifest.yml
          current_app_name: cube-untap
    - put: pivotal-tracker
      params:
        repos:
        - cube-ci
        - cube-draft
        - cube-untap
