platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
- name: cube-untap
- name: cube-ci

outputs:
- name: compiledApp

run:
  path: ./cube-ci/tasks/cube-untap/test-build.shsh
