platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
- name: cube-draft
- name: cube-ci

outputs:
- name: cube-draft-build

caches: 
- path: yarn-cache

params: {"YARN_CACHE_FOLDER" : "../yarn-cache"}

run:
  path: ./cube-ci/tasks/cube-draft/build.sh
  