platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/browsers
    tag: latest

inputs:
- name: cube-draft
- name: cube-ci

caches: 
- path: yarn-cache

params: {
  "YARN_CACHE_FOLDER": "../yarn-cache",
  "BACKEND_URL": "https://cube-untap-integ.cfapps.io/",
  "CYPRESS_baseUrl": "https://cube-draft-integ.cfapps.io/"
}

run:
  path: ./cube-ci/tasks/cube-draft/integration.sh
