platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
- name: cube-draft
- name: cube-ci

caches: 
- path: yarn-cache

run:
  path: ./cube-ci/tasks/cube-draft/test.sh

params: {"YARN_CACHE_FOLDER" : "yarn-cache"}